config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  resources :videos
  resources :publishers
  resources :get_free_consultants
  resources :publishers do
    resources :comments
  end
  resources :questions
  resources :advices
  resources :docteurs
  resources :welcome
  root 'welcome#index'
 
  resources :doctors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publisher
  validates :description, presence: true, uniqueness: true, length:{ maximum:100 }
end

app/models/docteur.rb
class Docteur < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
# validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_one_attached :image
    validates :names, :image, :email, :telephone, :availability, :upload_cv, :upload_diploma, :field_in,  presence: true
    validates :email, uniqueness: true
end

app/models/get_free_consultant.rb
class GetFreeConsultant < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :comments
    validates :name, presence: true, uniqueness: true, length:{ maximum:100 }
    validates :publish, presence: true, uniqueness: true, length:{ minimum:100 }
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    mount_uploader :file, VideoUploader
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  before_action :set_advice, only: [:show, :edit, :update, :destroy]

 
  def index
    @advices = Advice.all
  end

  
  def show
  end

  
  def new
    @advice = Advice.new
  end

 
  def edit
  end

  def create
    @advice = Advice.new(advice_params)

    
      if @advice.save
        redirect_to @advice, notice: 'Advice was successfully created.' 
      else
        render :new 
    end
  end


  def update
      if @advice.update(advice_params)
         redirect_to @advice, notice: 'Advice was successfully updated.'
      else
        render :edit 
    end
  end

  
  def destroy
    @advice.destroy
    
     redirect_to advices_url, notice: 'Advice was successfully destroyed.' 
     
  end

  private
    def set_advice
      @advice = Advice.find(params[:id])
    end

    def advice_params
      params.require(:advice).permit(:name, :field_in, :advice, :email, :time)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_publisher
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @publisher.comments.create(params[:comment].permit(:description))
@comment.save
if @comment.save
  redirect_to publisher_path(@publisher), notice: "Thank you for commomenting on this article"
else
  render 'new'
end
end
def destroy
@comment.destroy
redirect_to publisher_path(@publisher)
end
def edit
end
def update
  if @comment.update(params[:comment].permit(:description))
    redirect_to publisher_path(@publisher)
    else
      render 'edit'
    end
  end
  private
def find_publisher
  @publisher= Publisher.find(params[:publisher_id])
end
def find_comment
  @comment = @publisher.comments.find(params[:id])
end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
  end

  def new
    @question = Question.new
  end


  def edit
  end

  def create
    flash[:notice] = "Save the world by Giving life to helpless"
    redirect_to @show
    @question = Question.new(question_params)

    
      if @question.save
        redirect_to @question, notice: 'Thank you for asking!!! the doctors will help.'
      else
         render :new 
    end
  end

  def update
      if @question.update(question_params)
         redirect_to @question, notice: 'Question was successfully updated.' 
      else
         render :edit 
    end
  end

 
  def destroy
    @question.destroy
    
      redirect_to questions_url, notice: 'Question was successfully destroyed.' 
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:name, :question, :email, :time)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  
  def index
    @videos = Video.all
  end

  
  def show
  end

  
  def new
    @video = Video.new
  end

  
  def edit
  end

  
  def create
    @video = Video.new(video_params)

   
      if @video.save
         redirect_to @video, notice: 'Video was successfully created.' 
      else
         render :new
    end
  end

  
  def update
    
      if @video.update(video_params)
         redirect_to @video, notice: 'Video was successfully updated.' 
      else
        render :edit 
    end
  end

  def destroy
    @video.destroy
    
      redirect_to videos_url, notice: 'Video was successfully destroyed.' 
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :file)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docteurs_helper.rb
module DocteursHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_area :question %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.date_select :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Question</th>
      <th>Email</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.name %></td>
        <td><%= question.question %></td>
        <td><%= question.email %></td>
        <td><%= question.time %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @question.name %>
</p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Email:</strong>
  <%= @question.email %>
</p>

<p>
  <strong>Time:</strong>
  <%= @question.time %>
</p>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', welcome_index_path %>