config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  resources :videos
  resources :publishers
  resources :get_free_consultants
  resources :publishers do
    resources :comments
  end
  resources :questions
  resources :advices
  resources :docteurs
  resources :welcome
  root 'welcome#index'
 
  resources :doctors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publisher
  validates :description, presence: true, uniqueness: true, length:{ maximum:100 }
end

app/models/docteur.rb
class Docteur < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
# validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_one_attached :image
    validates :names, :image, :email, :telephone, :availability, :upload_cv, :upload_diploma, :field_in,  presence: true
    validates :email, uniqueness: true
end

app/models/get_free_consultant.rb
class GetFreeConsultant < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :comments
    validates :name, presence: true, uniqueness: true, length:{ maximum:100 }
    validates :publish, presence: true, uniqueness: true, length:{ minimum:100 }
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    mount_uploader :file, VideoUploader
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  before_action :set_advice, only: [:show, :edit, :update, :destroy]

 
  def index
    @advices = Advice.all
  end

  
  def show
  end

  
  def new
    @advice = Advice.new
  end

 
  def edit
  end

  def create
    @advice = Advice.new(advice_params)

    
      if @advice.save
        redirect_to @advice, notice: 'Advice was successfully created.' 
      else
        render :new 
    end
  end


  def update
      if @advice.update(advice_params)
         redirect_to @advice, notice: 'Advice was successfully updated.'
      else
        render :edit 
    end
  end

  
  def destroy
    @advice.destroy
    
     redirect_to advices_url, notice: 'Advice was successfully destroyed.' 
     
  end

  private
    def set_advice
      @advice = Advice.find(params[:id])
    end

    def advice_params
      params.require(:advice).permit(:name, :field_in, :advice, :email, :time)
    end
end

app/controllers/get_free_consultants_controller.rb
class GetFreeConsultantsController < ApplicationController
  before_action :set_get_free_consultant, only: [:show, :edit, :update, :destroy]

 
  def index
    @get_free_consultants = GetFreeConsultant.all
  end

  def show
  end

  def new
    @get_free_consultant = GetFreeConsultant.new
  end


  def edit
  end

  def create
    @get_free_consultant = GetFreeConsultant.new(get_free_consultant_params)
      if @get_free_consultant.save
        redirect_to @get_free_consultant, notice: 'Get free consultant was successfully created.' 
      else
        render :new 
      end
  end


  def update
      if @get_free_consultant.update(get_free_consultant_params)
        redirect_to @get_free_consultant, notice: 'Get free consultant was successfully updated.' 
      else
        render :edit 
    end
  end

  def destroy
    @get_free_consultant.destroy
       redirect_to get_free_consultants_url, notice: 'Get free consultant was successfully destroyed.' 
  end

  private
    def set_get_free_consultant
      @get_free_consultant = GetFreeConsultant.find(params[:id])
    end
    
    def get_free_consultant_params
      params.require(:get_free_consultant).permit(:name, :email, :phone, :address, :dob, :street_name, :district, :sector, :cell, :how_did_you_us, :height, :weight, :gender, :concern, :family_history, :subcribe_article, :time)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  
  def index
    @videos = Video.all
  end

  
  def show
  end

  
  def new
    @video = Video.new
  end

  
  def edit
  end

  
  def create
    @video = Video.new(video_params)

   
      if @video.save
         redirect_to @video, notice: 'Video was successfully created.' 
      else
         render :new
    end
  end

  
  def update
    
      if @video.update(video_params)
         redirect_to @video, notice: 'Video was successfully updated.' 
      else
        render :edit 
    end
  end

  def destroy
    @video.destroy
    
      redirect_to videos_url, notice: 'Video was successfully destroyed.' 
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :file)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docteurs_helper.rb
module DocteursHelper
end

app/helpers/get_free_consultants_helper.rb
module GetFreeConsultantsHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/get_free_consultants/_form.html.erb
<%= form_with(model: get_free_consultant, local: true) do |form| %>
  <% if get_free_consultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(get_free_consultant.errors.count, "error") %> prohibited this get_free_consultant from being saved:</h2>

      <ul>
        <% get_free_consultant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :street_name %>
    <%= form.text_area :street_name %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_area :district %>
  </div>

  <div class="field">
    <%= form.label :sector %>
    <%= form.text_area :sector %>
  </div>

  <div class="field">
    <%= form.label :cell %>
    <%= form.text_area :cell %>
  </div>

  <div class="field">
    <%= form.label :how_did_you_us %>
    <%= form.text_field :how_did_you_us %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_area :gender %>
  </div>

  <div class="field">
    <%= form.label :concern %>
    <%= form.text_field :concern %>
  </div>

  <div class="field">
    <%= form.label :family_history %>
    <%= form.text_field :family_history %>
  </div>

  <div class="field">
    <%= form.label :subcribe_article %>
    <%= form.text_field :subcribe_article %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.date_select :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/get_free_consultants/edit.html.erb
<h1>Editing Get Free Consultant</h1>

<%= render 'form', get_free_consultant: @get_free_consultant %>

<%= link_to 'Show', @get_free_consultant %> |
<%= link_to 'Back', get_free_consultants_path %>

app/views/get_free_consultants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Get Free Consultants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Dob</th>
      <th>Street name</th>
      <th>District</th>
      <th>Sector</th>
      <th>Cell</th>
      <th>How did you us</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Gender</th>
      <th>Concern</th>
      <th>Family history</th>
      <th>Subcribe article</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @get_free_consultants.each do |get_free_consultant| %>
      <tr>
        <td><%= get_free_consultant.name %></td>
        <td><%= get_free_consultant.email %></td>
        <td><%= get_free_consultant.phone %></td>
        <td><%= get_free_consultant.address %></td>
        <td><%= get_free_consultant.dob %></td>
        <td><%= get_free_consultant.street_name %></td>
        <td><%= get_free_consultant.district %></td>
        <td><%= get_free_consultant.sector %></td>
        <td><%= get_free_consultant.cell %></td>
        <td><%= get_free_consultant.how_did_you_us %></td>
        <td><%= get_free_consultant.height %></td>
        <td><%= get_free_consultant.weight %></td>
        <td><%= get_free_consultant.gender %></td>
        <td><%= get_free_consultant.concern %></td>
        <td><%= get_free_consultant.family_history %></td>
        <td><%= get_free_consultant.subcribe_article %></td>
        <td><%= get_free_consultant.time %></td>
        <td><%= link_to 'Show', get_free_consultant %></td>
        <td><%= link_to 'Edit', edit_get_free_consultant_path(get_free_consultant) %></td>
        <td><%= link_to 'Destroy', get_free_consultant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Get Free Consultant', new_get_free_consultant_path %>

app/views/get_free_consultants/new.html.erb
<h1>New Get Free Consultant</h1>

<%= render 'form', get_free_consultant: @get_free_consultant %>

<%= link_to 'Back', get_free_consultants_path %>

app/views/get_free_consultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @get_free_consultant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @get_free_consultant.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @get_free_consultant.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @get_free_consultant.address %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @get_free_consultant.dob %>
</p>

<p>
  <strong>Street name:</strong>
  <%= @get_free_consultant.street_name %>
</p>

<p>
  <strong>District:</strong>
  <%= @get_free_consultant.district %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @get_free_consultant.sector %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @get_free_consultant.cell %>
</p>

<p>
  <strong>How did you us:</strong>
  <%= @get_free_consultant.how_did_you_us %>
</p>

<p>
  <strong>Height:</strong>
  <%= @get_free_consultant.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @get_free_consultant.weight %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @get_free_consultant.gender %>
</p>

<p>
  <strong>Concern:</strong>
  <%= @get_free_consultant.concern %>
</p>

<p>
  <strong>Family history:</strong>
  <%= @get_free_consultant.family_history %>
</p>

<p>
  <strong>Subcribe article:</strong>
  <%= @get_free_consultant.subcribe_article %>
</p>

<p>
  <strong>Time:</strong>
  <%= @get_free_consultant.time %>
</p>

<%= link_to 'Edit', edit_get_free_consultant_path(@get_free_consultant) %> |
<%= link_to 'Back', get_free_consultants_path %>