config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  resources :videos
  resources :publishers
  resources :get_free_consultants
  resources :publishers do
    resources :comments
  end
  resources :questions
  resources :advices
  resources :docteurs
  resources :welcome
  root 'welcome#index'
 
  resources :doctors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publisher
  validates :description, presence: true, uniqueness: true, length:{ maximum:100 }
end

app/models/docteur.rb
class Docteur < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
# validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_one_attached :image
    validates :names, :image, :email, :telephone, :availability, :upload_cv, :upload_diploma, :field_in,  presence: true
    validates :email, uniqueness: true
end

app/models/get_free_consultant.rb
class GetFreeConsultant < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :comments
    validates :name, presence: true, uniqueness: true, length:{ maximum:100 }
    validates :publish, presence: true, uniqueness: true, length:{ minimum:100 }
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    mount_uploader :file, VideoUploader
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  before_action :set_advice, only: [:show, :edit, :update, :destroy]

 
  def index
    @advices = Advice.all
  end

  
  def show
  end

  
  def new
    @advice = Advice.new
  end

 
  def edit
  end

  def create
    @advice = Advice.new(advice_params)

    
      if @advice.save
        redirect_to @advice, notice: 'Advice was successfully created.' 
      else
        render :new 
    end
  end


  def update
      if @advice.update(advice_params)
         redirect_to @advice, notice: 'Advice was successfully updated.'
      else
        render :edit 
    end
  end

  
  def destroy
    @advice.destroy
    
     redirect_to advices_url, notice: 'Advice was successfully destroyed.' 
     
  end

  private
    def set_advice
      @advice = Advice.find(params[:id])
    end

    def advice_params
      params.require(:advice).permit(:name, :field_in, :advice, :email, :time)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_publisher
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @publisher.comments.create(params[:comment].permit(:description))
@comment.save
if @comment.save
  redirect_to publisher_path(@publisher), notice: "Thank you for commomenting on this article"
else
  render 'new'
end
end
def destroy
@comment.destroy
redirect_to publisher_path(@publisher)
end
def edit
end
def update
  if @comment.update(params[:comment].permit(:description))
    redirect_to publisher_path(@publisher)
    else
      render 'edit'
    end
  end
  private
def find_publisher
  @publisher= Publisher.find(params[:publisher_id])
end
def find_comment
  @comment = @publisher.comments.find(params[:id])
end
end

app/controllers/docteurs_controller.rb
class DocteursController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_docteur, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception

  # GET /docteurs
  # GET /docteurs.json
  def index
    @docteurs = Docteur.all
  end

  # GET /docteurs/1
  # GET /docteurs/1.json
  def show
  end

  # GET /docteurs/new
  def new
    @docteur = Docteur.new
  end

  
  def edit
  end

 
  def create
    @docteur = Docteur.new(docteur_params)
      if @docteur.save
        redirect_to @docteur, notice: 'Docteur was successfully created.'
      else
        render :new 
    end
  end


  def update
    if @docteur.update(docteur_params)
      redirect_to @docteur, notice: 'Docteur was successfully updated.' 
    else
      render :edit 
    end    
  end

  def destroy
    @docteur.destroy  
      redirect_to docteurs_url, notice: 'Docteur was successfully destroyed.' 
  end

  private
    def set_docteur
      @docteur = Docteur.find(params[:id])
    end

    def docteur_params
      params.require(:docteur).permit(:names, :field_in, :upload_cv, :upload_diploma,:image, :email, :availability, :telephone)
    end
end

app/controllers/publisher_controller.rb
class PublisherController < ApplicationController
  def create
  end

  def store
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :authenticate_user!, :except => [:show]
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception

  def index
    @publishers = Publisher.all
  end

  def show
    @comments = Comment.where(publisher_id: @publisher)
  end
  
  def new
    @publisher = Publisher.new
  end

  def edit
  end

  
  def create
    @publisher = Publisher.new(publisher_params)

      if @publisher.save
         redirect_to @publisher, notice: 'Publisher was successfully created.' 
      else
         render :new 
    end
  end

  def update
      if @publisher.update(publisher_params)
         redirect_to @publisher, notice: 'Publisher was successfully updated.' 
      else
         render :edit 
    end
  end

  def destroy
    @publisher.destroy
       redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' 
  end

  private
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    def publisher_params
      params.require(:publisher).permit(:name, :publish, :email, :time)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  
  def index
    @videos = Video.all
  end

  
  def show
  end

  
  def new
    @video = Video.new
  end

  
  def edit
  end

  
  def create
    @video = Video.new(video_params)

   
      if @video.save
         redirect_to @video, notice: 'Video was successfully created.' 
      else
         render :new
    end
  end

  
  def update
    
      if @video.update(video_params)
         redirect_to @video, notice: 'Video was successfully updated.' 
      else
        render :edit 
    end
  end

  def destroy
    @video.destroy
    
      redirect_to videos_url, notice: 'Video was successfully destroyed.' 
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :file)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docteurs_helper.rb
module DocteursHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/publisher/create.html.erb
<h1>Publisher#create</h1>
<p>Find me in app/views/publisher/create.html.erb</p>

app/views/publisher/store.html.erb
<h1>Publisher#store</h1>
<p>Find me in app/views/publisher/store.html.erb</p>

app/views/publishers/_form.html.erb
<%= form_with(model: publisher, local: true) do |form| %>
  <% if publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :publish %>
    <%= form.text_area :publish %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.date_select :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      
    </li>
    ...
  </ul>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publishers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Publish</th>
      <th>Email</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= publisher.publish %></td>
        <td><%= publisher.email %></td>
        <td><%= publisher.time %></td>
        <td><%= link_to 'Show', publisher %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form', publisher: @publisher %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @publisher.publish %>
</p>

<p>
  <strong>Email:</strong>
  <%= @publisher.email %>
</p>

<p>
  <strong>Time:</strong>
  <%= @publisher.time %>
</p>

<%= render 'comments/comment' %>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>
<p id="notice"><%= notice %></p>