config/routes.rb
Rails.application.routes.draw do
 devise_for :users
  resources :videos
  resources :publishers
  resources :get_free_consultants
  resources :publishers do
    resources :comments
  end
  resources :questions
  resources :advices
  resources :docteurs
  resources :welcome
  root 'welcome#index'
 
  resources :doctors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/advice.rb
class Advice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publisher
  validates :description, presence: true, uniqueness: true, length:{ maximum:100 }
end

app/models/docteur.rb
class Docteur < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
# validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    has_one_attached :image
    validates :names, :image, :email, :telephone, :availability, :upload_cv, :upload_diploma, :field_in,  presence: true
    validates :email, uniqueness: true
end

app/models/get_free_consultant.rb
class GetFreeConsultant < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :comments
    validates :name, presence: true, uniqueness: true, length:{ maximum:100 }
    validates :publish, presence: true, uniqueness: true, length:{ minimum:100 }
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    mount_uploader :file, VideoUploader
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  before_action :set_advice, only: [:show, :edit, :update, :destroy]

 
  def index
    @advices = Advice.all
  end

  
  def show
  end

  
  def new
    @advice = Advice.new
  end

 
  def edit
  end

  def create
    @advice = Advice.new(advice_params)

    
      if @advice.save
        redirect_to @advice, notice: 'Advice was successfully created.' 
      else
        render :new 
    end
  end


  def update
      if @advice.update(advice_params)
         redirect_to @advice, notice: 'Advice was successfully updated.'
      else
        render :edit 
    end
  end

  
  def destroy
    @advice.destroy
    
     redirect_to advices_url, notice: 'Advice was successfully destroyed.' 
     
  end

  private
    def set_advice
      @advice = Advice.find(params[:id])
    end

    def advice_params
      params.require(:advice).permit(:name, :field_in, :advice, :email, :time)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_publisher
 before_action :find_comment, only: [:destroy, :edit , :update]
def create
@comment = @publisher.comments.create(params[:comment].permit(:description))
@comment.save
if @comment.save
  redirect_to publisher_path(@publisher), notice: "Thank you for commomenting on this article"
else
  render 'new'
end
end
def destroy
@comment.destroy
redirect_to publisher_path(@publisher)
end
def edit
end
def update
  if @comment.update(params[:comment].permit(:description))
    redirect_to publisher_path(@publisher)
    else
      render 'edit'
    end
  end
  private
def find_publisher
  @publisher= Publisher.find(params[:publisher_id])
end
def find_comment
  @comment = @publisher.comments.find(params[:id])
end
end

app/controllers/docteurs_controller.rb
class DocteursController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_docteur, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception

  # GET /docteurs
  # GET /docteurs.json
  def index
    @docteurs = Docteur.all
  end

  # GET /docteurs/1
  # GET /docteurs/1.json
  def show
  end

  # GET /docteurs/new
  def new
    @docteur = Docteur.new
  end

  
  def edit
  end

 
  def create
    @docteur = Docteur.new(docteur_params)
      if @docteur.save
        redirect_to @docteur, notice: 'Docteur was successfully created.'
      else
        render :new 
    end
  end


  def update
    if @docteur.update(docteur_params)
      redirect_to @docteur, notice: 'Docteur was successfully updated.' 
    else
      render :edit 
    end    
  end

  def destroy
    @docteur.destroy  
      redirect_to docteurs_url, notice: 'Docteur was successfully destroyed.' 
  end

  private
    def set_docteur
      @docteur = Docteur.find(params[:id])
    end

    def docteur_params
      params.require(:docteur).permit(:names, :field_in, :upload_cv, :upload_diploma,:image, :email, :availability, :telephone)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  
  def index
    @videos = Video.all
  end

  
  def show
  end

  
  def new
    @video = Video.new
  end

  
  def edit
  end

  
  def create
    @video = Video.new(video_params)

   
      if @video.save
         redirect_to @video, notice: 'Video was successfully created.' 
      else
         render :new
    end
  end

  
  def update
    
      if @video.update(video_params)
         redirect_to @video, notice: 'Video was successfully updated.' 
      else
        render :edit 
    end
  end

  def destroy
    @video.destroy
    
      redirect_to videos_url, notice: 'Video was successfully destroyed.' 
  end

  private
    def set_video
      @video = Video.find(params[:id])
    end

    def video_params
      params.require(:video).permit(:title, :file)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/docteurs_helper.rb
module DocteursHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advices/_form.html.erb
<%= form_with(model: advice, local: true) do |form| %>
  <% if advice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advice.errors.count, "error") %> prohibited this advice from being saved:</h2>

      <ul>
        <% advice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :field_in %>
    <%= form.text_area :field_in %>
  </div>

  <div class="field">
    <%= form.label :advice %>
    <%= form.text_area :advice %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.date_select :time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/advices/edit.html.erb
<h1>Editing Advice</h1>

<%= render 'form', advice: @advice %>

<%= link_to 'Show', @advice %> |
<%= link_to 'Back', advices_path %>

app/views/advices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Field in</th>
      <th>Advice</th>
      <th>Email</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advices.each do |advice| %>
      <tr>
        <td><%= advice.name %></td>
        <td><%= advice.field_in %></td>
        <td><%= advice.advice %></td>
        <td><%= advice.email %></td>
        <td><%= advice.time %></td>
        <td><%= link_to 'Show', advice %></td>
        <td><%= link_to 'Edit', edit_advice_path(advice) %></td>
        <td><%= link_to 'Destroy', advice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advice', new_advice_path %>

app/views/advices/new.html.erb
<h1>New Advice</h1>

<%= render 'form', advice: @advice %>

<%= link_to 'Back', advices_path %>

app/views/advices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @advice.name %>
</p>

<p>
  <strong>Field in:</strong>
  <%= @advice.field_in %>
</p>

<p>
  <strong>Advice:</strong>
  <%= @advice.advice %>
</p>

<p>
  <strong>Email:</strong>
  <%= @advice.email %>
</p>

<p>
  <strong>Time:</strong>
  <%= @advice.time %>
</p>

<%= link_to 'Edit', edit_advice_path(@advice) %> |
<%= link_to 'Back', advices_path %>

app/views/comments/_comment.html.erb
<ul>
  <% @comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <p><br><%= comment.description%><br>
        <% if user_signed_in? && current_user.id  %>
        <%= link_to "delete", [comment.publisher, comment], method: :delete, class:"genric-btn danger-border circle" %>
        <%= link_to "edit ", edit_publisher_comment_path(comment.publisher, comment), class:"genric-btn success-border circle" %></p>
        </li>
        <% end %>
    <% end %>
  <% end %>
<%= render 'comments/form'%>
</ul>

app/views/comments/_form.html.erb
<%= form_for ([@publisher, @publisher.comments.build]) do |f| %>
  <div class="form-group">
  <%= f.text_area :description, class:"single-input", placeholder:"enter comment", class: "form-control"%>
  <%= f.submit " comment", class:"genric-btn info-border circle", class: "btn btn-primary"  %>
  </div>
<%end%>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
    <div id="comments_<%= comment.id %>" class="row single-comment">
      <td><p><%= comment.name %></p></td>&nbsp;&nbsp;
      <td> <p><%= comment.description %></p></td>
      <div id="comment_<%= comment.id %>" class="row single-comment vertical-align">
      <%= button_to(publisher_comment_path(@publisher.id,comment.id), {method: :delete, remote: true, style:" width:40px",value:'delete', params:{id: comment.id, publisher: publisher.id}} ) do%>
      <i class="glyphicon glyphicon-trash" ></i>
    <% end %>
</div>
    <% end %>
  <% end %>
</ul>

app/views/comments/destroy.js.erb
$('#comments_<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<%= form_for ([@publisher, @comment]) do |f| %>
    <%= f.text_area :description, class:"single-input"%>
    <%= f.submit "publisher comment", class:"genric-btn info-border circle" %>
<%end%>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.publisher.comments, publisher: @comment.publisher }) %>")
$("textarea").val('')
$("textfield").val('')

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @comment.publisher_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/docteurs/_form.html.erb
<%= form_with(model: docteur, local: true, html: { multipart: true } ) do |form| %>
  <% if docteur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(docteur.errors.count, "error") %> prohibited this docteur from being saved:</h2>

      <ul>
        <% docteur.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :names %>
    <%= form.text_field :names %>
  </div>

  <div class="field">
    <%= form.label :field_in %>
    <%= form.text_field :field_in %>
  </div>

  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
</div>

  <div class="field">
    <%= form.label :upload_cv %>
    <%= form.file_field :upload_cv %>
  </div>

  <div class="field">
    <%= form.label :upload_diploma %>
    <%= form.file_field :upload_diploma %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.text_field :availability %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <%= yield %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %><br>

<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/questions/new">Ideas</a>
    </li>
    ...
  </ul>
<% end %>

app/views/docteurs/edit.html.erb
<h1>Editing Docteur</h1>

<%= render 'form', docteur: @docteur %>

<%= link_to 'Show', @docteur %> |
<%= link_to 'Back', docteurs_path %>
<p id="notice"><%= notice %></p>

app/views/docteurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Welcome to Docteurs Page</h1><br><br>

<% @docteurs.each do |docteur| %>
  <div class="row">
  <div class = "col-sm-4">
  <% if docteur.image.present? %>
  <%= image_tag docteur.image , class:'image'%>
  <% end %>
  <div class="card-body mt-3"
  <h1><%= docteur.names %></h1>
  <p>
  <%= docteur.telephone %><br>
  <%= docteur.email %><br>
  <%= docteur.availability %>
  </p>
  </div
  <p class="card-footer">
  <%= link_to 'Back', docteurs_path, class:'btn btn-dark' %></p>
</div>
<% end %>
</div>
</div>
<%= link_to 'New Docteur', new_docteur_path %>

app/views/docteurs/new.html.erb
<h1>New Docteur</h1>

<%= render 'form', docteur: @docteur %>
<p id="notice"><%= notice %></p>

<%= link_to 'Back', docteurs_path %>

app/views/docteurs/show.html.erb
<div class="card">
  <%= image_tag @docteur.image , class:'image'%>
  <div class="card-body mt-3"
  <h1><%= @docteur.names %></h1>
  <p>
  <%= @docteur.telephone %><br>
  <%= @docteur.email %><br>
  <%= @docteur.availability %>
  </p>
  </div
  <p class="card-footer">
  <%= link_to 'Back', docteurs_path, class:'btn btn-dark' %></p>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true, html: { multipart: true }) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :video_title %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file, id: :video_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to Video page ,This viedo have taken from internet</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><p>
        <strong>File:</strong>
        <video controls width="640" height="480" src="<%= video.file %>"></video>
      </p></td>
        
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>File:</strong>
  <video controls width="640" height="480" src="<%= @video.file %>"></video>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>